version: '3'
services:
  web:
    build:
      context: web
      target: dev
    ports:
      - 80:80
    volumes:
      - ./web/src:/usr/share/nginx/src
    environment:
      REBOOTER_HOST: rebooter:3000
      APP_HOST: localhost:3000
    working_dir: /usr/share/nginx/src
  app:
    build: app
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/usr/src/app
    env_file:
      - ./app/.env
    command: sh
  rebooter:
    build: camera/rebooter
    tty: true
    volumes:
      - ./camera/rebooter/src:/usr/src/app
  level-sender:
    build: camera/level-sender
    tty: true
    volumes:
      - ./camera/level-sender/src:/usr/src/app
    command: sh
